### ISSUE TITLE
[remocon] implement request_interaction service

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_web_gui#21]
Currently web remocon has wrong logic to start interactions. 

[Here](https://github.com/robotics-in-concert/rocon_web_gui/blob/indigo/rocon_web_remocon/www/index.js#L517-L535) should be similar to [this logic](https://github.com/robotics-in-concert/rocon_qt_gui/blob/indigo/rocon_remocon/src/rocon_remocon/interactive_client_interface.py#L187-L222) in QT version of rocon remocon

**Comment by dwlee** [comment]
I update b97b1f2d995ced91c5301b7f296c547e493555b1
